server:
  port: ${PORT:8888}

app:
  api-prefix: ${API_PREFIX:/api}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: ${PROFILE_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=1
        - id: file_service
          uri: ${FILE_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=1
        - id: post_service
          uri: ${POST_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=1
        - id: notification_service
          uri: ${NOTIFICATION_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=1
        - id: chat_service
          uri: ${CHAT_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=1