server:
  port: ${PORT:8888}

app:
  api-prefix: ${API_PREFIX:/api}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8080}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1