### Login
POST {{gateway_url}}{{api_prefix}}/identity/auth/token
Content-Type: application/json

{
  "username": "zayden",
  "password": "12345678"
}

> {%
    client.global.set("auth_token", response.body.result.token)
 %}

### Get all Users
GET {{gateway_url}}{{api_prefix}}/identity/users/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get User
GET {{gateway_url}}{{api_prefix}}/identity/users/b43da07e-b5c9-463a-928b-d28813e135c5
Accept: application/json
Authorization: Bearer {{auth_token}}

###