### Registration
POST {{gateway_url}}{{api_prefix}}/identity/users/registration
Content-Type: application/json

{
  "username": "zayden",
  "password": "12345678",
  "firstName": "Tran Tin",
  "lastName": "Vo",
  "dob": "1993-09-02",
  "email": "votrantin@gmail.com",
  "city": "Ho Chi Minh"
}

### Login (Get Token)
POST {{gateway_url}}{{api_prefix}}/identity/auth/token
Content-Type: application/json

{
  "username": "zayden",
  "password": "12345678"
}

> {%
    client.global.set("auth_token", response.body.result.token)
 %}

### Get all Users
GET {{gateway_url}}{{api_prefix}}/identity/users/getAll
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get User
GET {{gateway_url}}{{api_prefix}}/identity/users/b43da07e-b5c9-463a-928b-d28813e135c5
Accept: application/json
Authorization: Bearer {{auth_token}}

### Update Profile
PUT {{gateway_url}}{{api_prefix}}/profile/users/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstName": "Tran Tin",
  "lastName": "Vo",
  "dob": "1993-09-02",
  "city": "Ho Chi Minh"
}

### Get Profile by userId
GET http://localhost:8081/profile/internal/users/f45aa0d4-3e63-456e-8d93-c39e91aec4ae
Accept: application/json

### Update Avatar
PUT {{gateway_url}}{{api_prefix}}/profile/users/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="20180809_133406.jpg"
Content-Type: image/png

< E:\photo\20180809_133406.jpg
--WebAppBoundary--

### Upload File
POST {{gateway_url}}{{api_prefix}}/file/media/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{auth_token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="20180809_133406.jpg"
Content-Type: image/png

< E:\photo\20180809_133406.jpg
--WebAppBoundary--

### Download File
GET {{gateway_url}}{{api_prefix}}/file/media/download/f0aac3f1-512b-470c-b239-f19ededbf318.jpg
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create Post
POST {{gateway_url}}{{api_prefix}}/post/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "1st post",
  "content": "This is the first post!"
}

### Get My Posts
GET {{gateway_url}}{{api_prefix}}/post/my-posts
Accept: application/json
Authorization: Bearer {{auth_token}}

###