server:
  port: ${PORT:8083}
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${DB_URI:mongodb://root:123456@localhost:27017/post-service?authSource=admin}

app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}